# app/swagger_docs.yml

swagger: "2.0"
info:
  version: "1.0.0"
  title: "Pokemon Game API"
  description: "API for a Pokemon Game"

schemes:
  - "http"
  - "https"

paths:
  /signup:
    post:
      tags:
        - "Authentication"
      summary: "Create a new user"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            required:
              - "username"
              - "email"
              - "password"
              - "first_name"
              - "last_name"
            properties:
              username:
                type: "string"
              email:
                type: "string"
              password:
                type: "string"
              first_name:
                type: "string"
              last_name:
                type: "string"
      responses:
        201:
          description: "User created successfully"
        400:
          description: "User already exists"

  /login:
    post:
      tags:
        - "Authentication"
      summary: "Login a user"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            required:
              - "username"
              - "password"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Login successful"
        401:
          description: "Invalid credentials"

  /logout:
    post:
      tags:
        - "Authentication"
      summary: "Logout a user"
      responses:
        200:
          description: "Logout successful"

  /profile/{user_id}:
    get:
      tags:
        - "User"
      summary: "Get user profile"
      parameters:
        - name: "user_id"
          in: "path"
          type: "integer"
          required: true
          description: "ID of the user"
      responses:
        200:
          description: "Profile retrieved successfully"
        404:
          description: "User not found"
    put:
      tags:
        - "User"
      summary: "Update user profile"
      parameters:
        - name: "user_id"
          in: "path"
          type: "integer"
          required: true
          description: "ID of the user"
        - in: "body"
          name: "body"
          schema:
            type: "object"
            properties:
              first_name:
                type: "string"
              last_name:
                type: "string"
      responses:
        200:
          description: "Profile updated successfully"
        404:
          description: "User not found"
